### ISSUE TITLE
I'd like to review the code to adapt it to my project

### ISSUE THREAD

**Issue by pcompassion** [EugeneHoran/Android-Material-SearchView#1]
README says `The code is a little messy, not using it any of my applications as of now.`

Which part do you think is messy so I can take a look before using it in my project.

**Comment by EugeneHoran** [comment]
Hey it was just put together as a fun project.  If you like I can put together a Search View for your project. Just let me know what you need.

**Comment by EugeneHoran** [comment]
@pcompassion If you want me to put together a new search let me know and I will I have a little free time rite now. I will be very busy this week with work.

**Comment by pcompassion** [comment]
very nice of you.

If you still have time, I could use some help.

I'd like to show list of popular search keywords in one tab and past search terms in another tab when user activates a searchview by clicking on the textview.

(When a user starts typing, I'd like to show another list of keywords filtered by the typed text. I can do this part I guess)

Would it be doable?

**Comment by EugeneHoran** [comment]
Yea I can give you a hand.  Just be specific on how you want it hooked up. Tabs as in TabLayout? if so,  Tab 1, will contain "Popular Search Keywords".  Tab 2, will contain a list of "Past Search Terms".  When the user starts typing you want a dropdown list below the search field with filtered data based on their text. Is that correct?

**Comment by pcompassion** [comment]
yes. more or less. although I'm not sure what that layout is called.
Usually there's one list view under searchview, but I want two list views,
one in each tab.

2015-11-12 3:51 GMT+09:00 Eugene Horan <notifications@github.com>:

**Comment by EugeneHoran** [comment]
Can you send an image of an example or draw it out so I get a better
understanding?
