### ISSUE TITLE
Remove sensitive data from Globals

### ISSUE THREAD

**Issue by jd-alexander** [EugeneHoran/Android-Material-SearchView#3]
I noticed that there's the app secret and several other pieces of sensitive materials in the Globals class. Probably won't cause any harm but it would be good to remove them from the repo :smiley:

**Comment by EugeneHoran** [comment]
Hey thanks for the heads up. I actually created a dummy account for these
examples. I am currently not using that account for anything other than
example.

**Comment by jd-alexander** [comment]
Ok awesome :+1:
